const CHANGE_ADD_LIST_STATUS ="CHANGE_ADD_LIST_STATUS"
const ADD_NEW_LIST ='ADD_NEW_LIST'
const ADD_NEW_ITEM ='ADD_NEW_ITEM'
const DELETE_LIST ='DELETE_LIST'
const DELETE_TASK = 'DELETE_TASK'

export {CHANGE_ADD_LIST_STATUS,ADD_NEW_LIST,ADD_NEW_ITEM,DELETE_LIST,DELETE_TASK}